class LocationCityDetails {
  String currentcity;
  String markets;
  String rainfall;
  String temperature;
  String soilType;
  String soilPh;
  String availableWaterBodies;
  String tractability;
  String soilNutrients;
  int id;
  LocationCityDetails({
    required this.currentcity,
    required this.markets,
    required this.rainfall,
    required this.temperature,
    required this.soilType,
    required this.soilPh,
    required this.availableWaterBodies,
    required this.tractability,
    required this.soilNutrients,
    required this.id,
  });
}

final List<LocationCityDetails> locationDetailsItems = <LocationCityDetails>[
  LocationCityDetails(
    id: 0,
    currentcity: "Agbogugu",
    markets: " Orio Agbogugu",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Deep clay loam soil",
    soilPh: "5.5 - 6.5",
    availableWaterBodies: "Nvula Agbogugu",
    soilNutrients: '5:6:15',
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 1,
    currentcity: "Amoli",
    markets: " Nkwo Uda-amoli",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Deep clay loam soil",
    soilPh: "5.0 - 6.5",
    availableWaterBodies: "Anizi River",
    soilNutrients: '8:5:15',
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 2,
    currentcity: "Awgu",
    markets: "  Orio Awgu",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Alluvial Soil",
    soilPh: "5.5 - 6.5",
    availableWaterBodies: "Null",
    soilNutrients: '57:100:192',
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 3,
    currentcity: "Ezere",
    markets: " Nkwo Ezere",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Deep clay loam soil",
    soilPh: "5.0 - 6.5",
    availableWaterBodies: "Iyioma",
    soilNutrients: '7:12:22',
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 4,
    currentcity: "Mgbidi",
    markets: " Nkwo Mgbidi",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Sandy loam soil",
    soilPh: "5.0 - 6.0",
    availableWaterBodies: "  4 catchments",
    soilNutrients: '7:17:27',
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 5,
    currentcity: "Ihe",
    markets: " Eke Ihe",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Sandy loam soil",
    soilPh: "5.0 - 6.0",
    availableWaterBodies: " null",
    soilNutrients: '19:21:46',
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 6,
    currentcity: "Mgbowo",
    markets: " Eke Mgbowo",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Alluvial soil",
    soilPh: "5.0 - 6.5",
    availableWaterBodies: "Ezioha dam",
    soilNutrients: '15:14:38',
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 7,
    currentcity: "Mmaku",
    markets: " Aho Mmaku, Eke Mmaku",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Shallow lithosol soil",
    soilPh: "5.0 - 6.5",
    availableWaterBodies: "Mmamu River,Mmaku",
    soilNutrients: '7:11:17',
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 8,
    currentcity: "Nkwe",
    markets: "  Eke Nkwe",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "shallow lithosol soil",
    soilPh: "5.0 - 6.0",
    soilNutrients: '8:12:17',
    availableWaterBodies: "Ezioha dam",
    tractability: "loading...",
  ),
  LocationCityDetails(
    id: 9,
    currentcity: "Oweli",
    markets: " Nkwo Oweli",
    rainfall: 'loading..',
    temperature: 'loading...',
    soilType: "Sandy clay loam soil",
    soilPh: "5.0 - 6.0",
    soilNutrients: '8:9:24',
    availableWaterBodies: "Iyi Ndi Amabo",
    tractability: "loading...",
  ),
];
